"""
Phase 5: Patch Engine
Generates remediation patches for confirmed vulnerabilities.
Uses LLM to produce code diffs based on findings and source code.
"""
import re
import asyncio
from typing import Optional
from dataclasses import dataclass

from llm.router import Router
from models.types import Finding


PATCH_SYSTEM_PROMPT = """You are a smart contract security patch generator. Given a vulnerability finding and source code, produce a minimal, correct patch.

Rules:
1. Output ONLY the patched function(s), not the entire contract
2. Use standard Solidity patterns for fixes
3. Include the original function signature
4. Mark removed lines with - and added lines with +
5. Provide a brief explanation of the fix
6. If the fix requires architectural changes, explain what needs to change

Common fix patterns:
- Reentrancy: Add nonReentrant modifier or checks-effects-interactions
- Access control: Add onlyOwner or role-based modifier
- Arithmetic: Use SafeMath or Solidity 0.8+ built-in checks
- Oracle manipulation: Add staleness checks, use TWAP
- Flash loan: Add same-block manipulation protection
"""


@dataclass
class PatchResult:
    finding_title: str
    severity: str
    original_code: str
    patched_code: str
    explanation: str
    function_name: str
    success: bool = True
    error: str = ""


async def generate_patch(
    source_code: str,
    finding: Finding,
    router: Optional[Router] = None,
) -> PatchResult:
    """Generate a remediation patch for a confirmed finding."""
    result = PatchResult(
        finding_title=finding.title,
        severity=finding.severity,
        original_code="",
        patched_code="",
        explanation="",
        function_name=finding.affected_functions[0] if finding.affected_functions else "",
    )

    if router is None or not router.is_configured():
        result.success = False
        result.error = "LLM router not configured"
        return result

    # Extract affected function(s) from source
    affected_code = _extract_function(source_code, result.function_name)
    if not affected_code:
        affected_code = source_code[:3000]

    result.original_code = affected_code

    prompt = (
        f"## Vulnerability\n"
        f"Title: {finding.title}\n"
        f"Severity: {finding.severity}\n"
        f"Category: {finding.category}\n"
        f"Description: {finding.description}\n"
        f"Affected function: {result.function_name}\n"
        f"Remediation: {finding.remediation}\n\n"
        f"## Source Code\n```solidity\n{affected_code[:3000]}\n```\n\n"
        f"## Task\nGenerate a patch for this vulnerability. Output format:\n"
        f"### Patched Code\n```solidity\n<patched function>\n```\n"
        f"### Explanation\n<brief explanation>"
    )

    resp = await asyncio.to_thread(router.call, "documenter", PATCH_SYSTEM_PROMPT, prompt, temperature=0.2, max_tokens=2048)

    if not resp.success or not resp.content:
        result.success = False
        result.error = resp.error or "LLM call failed"
        return result

    # Parse LLM response
    patched_code = _extract_code_block(resp.content, "solidity")
    explanation = _extract_section(resp.content, "### Explanation")

    result.patched_code = patched_code or affected_code
    result.explanation = explanation or "Patch generated by LLM"

    return result


def _extract_function(source_code: str, function_name: str) -> str:
    """Extract a function and its body from Solidity source."""
    if not function_name:
        return ""

    # Match function declaration and body
    pattern = rf'((?:function\s+{re.escape(function_name)}\s*\([^)]*\)[^{{]*{{)(?:[^{{}}]*{{[^{{}}]*\}})*[^{{}}]*\}})'
    match = re.search(pattern, source_code, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try modifier pattern
    pattern = rf'((?:modifier\s+{re.escape(function_name)}\s*\([^)]*\)[^{{]*{{)(?:[^{{}}]*{{[^{{}}]*\}})*[^{{}}]*\}})'
    match = re.search(pattern, source_code, re.DOTALL)
    if match:
        return match.group(1).strip()

    return ""


def _extract_code_block(text: str, lang: str = "") -> str:
    """Extract the first code block from markdown text."""
    pattern = rf'```{lang}\n(.*?)```'
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()
    # Fallback: try any code block
    match = re.search(r'```\n(.*?)```', text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def _extract_section(text: str, header: str) -> str:
    """Extract text after a markdown header."""
    pattern = rf'{re.escape(header)}\n(.*?)(?:\n###|\n##|\Z)'
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""
