from datetime import datetime
import pathlib
from agents.audit_agent import Finding


class AuditReportGenerator:
    def generate(self, findings: list[Finding], source_file: str = "", project_name: str = "Unknown") -> str:
        lines = []
        lines.append(f"# Security Audit Report — {project_name}")
        lines.append(f"")
        lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d')}")
        lines.append(f"**Source:** `{source_file}`")
        lines.append(f"**Tool:** Gaolaif Protocol Mode v2.0")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")
        lines.append(f"## Summary")
        lines.append(f"")
        lines.append(f"| Severity | Count |")
        lines.append(f"|----------|-------|")

        severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for f in findings:
            sev = f.severity.upper()
            if sev in severity_counts:
                severity_counts[sev] += 1

        for sev, count in severity_counts.items():
            if count > 0:
                lines.append(f"| {sev} | {count} |")

        lines.append(f"")
        lines.append(f"**Total Findings:** {len(findings)}")
        lines.append(f"")

        if findings:
            lines.append(f"## Findings")
            lines.append(f"")

            for i, finding in enumerate(findings, 1):
                lines.append(f"### {i}. [{finding.severity}] {finding.title}")
                lines.append(f"")
                lines.append(f"**Contract:** `{finding.contract_name or source_file}`")
                if finding.affected_function:
                    lines.append(f"**Function:** `{finding.affected_function}`")
                if finding.line_number:
                    lines.append(f"**Line:** {finding.line_number}")
                lines.append(f"")
                lines.append(f"{finding.description}")
                if finding.attack_vector:
                    lines.append(f"")
                    lines.append(f"*Attack vector: {finding.attack_vector}*")
                lines.append(f"")

        lines.append(f"---")
        lines.append(f"*Report generated by Gaolaif v2.0 — gaolaif.io*")

        report = "\n".join(lines)

        out_path = pathlib.Path.cwd() / f"gaolaif-audit-{datetime.now().strftime('%Y%m%d-%H%M')}.md"
        out_path.write_text(report)

        return report
